-- Insert sample recipes
INSERT INTO RECIPES (ID, NAME, VIEW_COUNT, CREATED_DATE, MODIFY_DATE, DIFFICULTY, IMAGE_URL)
VALUES (1, 'Wagyu Burger', 15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'EASY', ' https://ddg0cip9uom1w.cloudfront.net/code-challenge/burger.jpg');

INSERT INTO RECIPES (ID, NAME, VIEW_COUNT, CREATED_DATE, MODIFY_DATE, DIFFICULTY, IMAGE_URL)
VALUES (2, 'Cheese Burger', 10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'MEDIUM', 'https://ddg0cip9uom1w.cloudfront.net/code-challenge/burger.jpg');

INSERT INTO RECIPES (ID, NAME, VIEW_COUNT, CREATED_DATE, MODIFY_DATE, DIFFICULTY, IMAGE_URL)
VALUES (3, 'Bacon Burger', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'HARD', 'https://ddg0cip9uom1w.cloudfront.net/code-challenge/burger.jpg');

INSERT INTO RECIPES (ID, NAME, VIEW_COUNT, CREATED_DATE, MODIFY_DATE, DIFFICULTY, IMAGE_URL)
VALUES (4, 'Chicken Burger', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'EASY', 'https://ddg0cip9uom1w.cloudfront.net/code-challenge/burger.jpg');

INSERT INTO RECIPES (ID, NAME, VIEW_COUNT, CREATED_DATE, MODIFY_DATE, DIFFICULTY, IMAGE_URL)
VALUES (5, 'Breakfast Burger', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'MEDIUM', 'https://ddg0cip9uom1w.cloudfront.net/code-challenge/burger.jpg');

-- Insert sample ingredients
INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (1, 'Burger Bun', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'pc');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (2, 'Lettuce', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'pc');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (3, 'Onions', 0.25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'cup');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (4, 'Ground Wagyu Beef', 0.25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'lbs');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (5, 'Burger Bun', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 'pc');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (6, 'Cheddar Cheese', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 'slice');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (7, 'Ground Beef', 0.25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 'lbs');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (8, 'Bacon Strips', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 'pcs');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (9, 'Burger Bun', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 'pc');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (10, 'Cheddar Cheese', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 'slice');

INSERT INTO INGREDIENTS (ID, NAME, QUANTITY, CREATED_DATE, MODIFY_DATE, RECIPE_ID, UNIT)
VALUES (11, 'Ground Beef', 0.25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 'lbs');
